# Generated by Django 6.0.4 on 2026-05-02 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_id', models.CharField(max_length=10)),
                ('entity_name', models.CharField(max_length=200)),
                ('about', models.TextField()),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('organizer', 'Organizer'), ('admin', 'Admin')], max_length=20)),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
