# Generated by Django 6.0.4 on 2026-05-03 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rep_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
