# Generated by Django 6.0.4 on 2026-05-03 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('initiatives', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_number', models.CharField(max_length=50, unique=True)),
                ('qr_code', models.ImageField(blank=True, upload_to='permits/qrs/')),
                ('pdf_file', models.FileField(blank=True, upload_to='permits/pdfs/')),
                ('permit_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('starts_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('initiative', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permit', to='initiatives.initiative')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permits', to='accounts.profile')),
            ],
        ),
    ]
