# Generated by Django 6.0.4 on 2026-05-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='permit_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], max_length=20),
        ),
    ]
