# Generated by Django 6.0.4 on 2026-05-03 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0002_alter_permit_permit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='permit_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('not requested', 'Not Requested')], default='not requested', max_length=20),
        ),
    ]
